### ISSUE TITLE
Using angular.copy(...) on a model instance

### ISSUE THREAD

**Issue by juristr** [Swimlane/model-factory#19]
[As mentioned](https://github.com/phxdatasec/model-factory/issues/7#issuecomment-64932686) in #7 using `angular.copy(..)` on some model instance causes some issues due to the presence of a bug like

```javascript
var someModel = new PersonModel({
   id: 1,
   name: 'Juri'
});

var aCopy = angular.copy(someModel);
aCopy.name = 'Austin';

aCopy.$save();
```

This code would send back `{ id: 1, name: 'Juri' }` instead of the expected `{ id: 1, name: 'Austin' }`.

---

The fix is quite easy and it works already on my branch locally ( #15 ). However, there are some design decisions I'd like to discuss...

**What happens when I invoke `$delete` on a model list??**  
IMHO, a copy on a single model instance should "detach" it from the list. Any deletions of modifications should not have an impact on the overall list but be fully isolated. That's what I would expect as a developer. _(Maybe we could add a utility function for then merging a "detached" entity back into the list..i.e. after receiving it back from the server..)_

(I'm looking into the code whether there are other scenarios to be handled as well...)

**Comment by amcdnl** [comment]
I believe this is solved now by the other PR?

**Comment by juristr** [comment]
exactly
